`Array` - An array is a data structure that stores a collection of elements of the same data type in contiguous memory locations.

### **1. Arrays**

In [1]:
import array

In [2]:
# creation

arr1 = array.array('i', [10, 20, 30, 40, 50])
print(arr1)

array('i', [10, 20, 30, 40, 50])


In [3]:
# access

arr1[2]

30

In [4]:
arr1[-2]

40

In [5]:
# traversal
for element in arr1:
    print(element, end=' ')

10 20 30 40 50 

In [6]:
# insertion
arr1.insert(3, 35) # (index, value)
print(arr1)

array('i', [10, 20, 30, 35, 40, 50])


In [7]:
# deletion
arr1.remove(30) # remove the first occurrence of value
print(arr1)

array('i', [10, 20, 35, 40, 50])


In [8]:
# updation
arr1[2] = 30 
print(arr1)

array('i', [10, 20, 30, 40, 50])


In [9]:
arr2 = array.array('i', [60, 70, 80])

In [10]:
# sorting
arr3= array.array('i', [4,6,3,9,5,2])
print(arr3)

array('i', [4, 6, 3, 9, 5, 2])


In [11]:
array.array('i', sorted(arr3)) # sorted one

array('i', [2, 3, 4, 5, 6, 9])

In [12]:
# merging
arr4 = arr1 + arr2 
print(arr4)

array('i', [10, 20, 30, 40, 50, 60, 70, 80])


In [13]:
# spliting
ix = int(len(arr4) / 2)
ix

4

In [14]:
arr4[: ix] 

array('i', [10, 20, 30, 40])

In [15]:
arr4[ix :]

array('i', [50, 60, 70, 80])

### **2. Numpy**

In [16]:
import numpy as np

In [17]:
# creation
np1= np.array([10, 20, 30, 40, 50])
np2= np.array([50, 60, 70, 80])
print(np1)
print(np2)

[10 20 30 40 50]
[50 60 70 80]


In [18]:
# access
np1[2].item()

30

In [19]:
# traversal
for element in np1:
    print(element, end=' ')

10 20 30 40 50 

In [20]:
# insertion
np1 = np.insert(np1, 3, 35) # (array, index, value)
print(np1)

[10 20 30 35 40 50]


In [21]:
np.insert(np1, 3, 37)

array([10, 20, 30, 37, 35, 40, 50])

In [22]:
# deletion
np.delete(np1, 3) # (array, index)

array([10, 20, 30, 40, 50])

In [23]:
# updation
np1[2] = 30
print(np1)

[10 20 30 35 40 50]


In [24]:
# sorting
np3 = np.array([4,6,3,9,5,2])
print(np3)

[4 6 3 9 5 2]


In [25]:
np.sort(np3)

array([2, 3, 4, 5, 6, 9])

In [26]:
# merging
np4= np.concatenate((np1, np2))
np4

array([10, 20, 30, 35, 40, 50, 50, 60, 70, 80])

In [27]:
# splitting

np.array_split(np4, 2) 

[array([10, 20, 30, 35, 40]), array([50, 50, 60, 70, 80])]