### 2D Operation

##### Creation

In [1]:
# creation

matrix = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

type(matrix) # it is still a list, just a list of lists

list

In [2]:
def display_matrix(matrix): # display function
    for row in matrix:
        print(row)  

In [3]:
display_matrix(matrix)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


##### Traversal

In [4]:
# traversal

for row in matrix:
    for element in row:
        print(element, end= ' ')
    print() # for new line after each row 

1 2 3 
4 5 6 
7 8 9 


In [5]:
# a safer way to traverse the matrix using indices

for i in range(len(matrix)):
    for j in range(len(matrix[i])):
        print(matrix[i][j], end= ' ')
    print() # for new line after each row

1 2 3 
4 5 6 
7 8 9 


In [6]:
matrix[2][0] # access element at third row and first column

7

##### Updation

In [7]:
# updation

matrix[0][1] = 20 # update element at first row and second column to 20
display_matrix(matrix)

[1, 20, 3]
[4, 5, 6]
[7, 8, 9]


In [8]:
# insertion

matrix[2].insert(1, 50) # insert 50 at second column of third row
display_matrix(matrix)

[1, 20, 3]
[4, 5, 6]
[7, 50, 8, 9]


In [9]:
matrix[0].append(30) # append 30 at the end of first row
display_matrix(matrix)

[1, 20, 3, 30]
[4, 5, 6]
[7, 50, 8, 9]


##### Deletion

In [10]:
# deletion

matrix[2].remove(50) # remove 50 from third row
display_matrix(matrix)

[1, 20, 3, 30]
[4, 5, 6]
[7, 8, 9]


In [11]:
matrix[0].pop() # remove last element from first row
display_matrix(matrix)

[1, 20, 3]
[4, 5, 6]
[7, 8, 9]


### 3D Operation

In [12]:
threeD_list = [ [[1, 2, 3]], [[4, 5, 6]], [[7, 8, 9]] ]
type(threeD_list) # it is still a list, just a list of lists of lists

list

In [13]:
for i in range(len(threeD_list)):
    for j in range(len(threeD_list[i])):
        for k in range(len(threeD_list[i][j])):
            print(threeD_list[i][j][k], end= ' ')
    print() # for new line after each row

1 2 3 
4 5 6 
7 8 9 


`Array` is homogeneous which support one data type and `List` is heterogeneous which supports many.

In [14]:
# Vectorization
import numpy as np

np1 = np.array([10, 20, 35, 40, 50])
np1

array([10, 20, 35, 40, 50])

In [15]:
np1 + 10 # adds 10 to each element of the array

array([20, 30, 45, 50, 60])

In [16]:
np1 * 2 # multiplies each element of the array by 2 

array([ 20,  40,  70,  80, 100])

In [17]:
np3 = np.array([4,5])
np4 = np.array([6,7])

np3 * np4 # multiplies corresponding elements of the two arrays

array([24, 35])

In [18]:
li1 = [4,5,6]
li1 +10 # this will give an error because we cannot add a scalar to a list

TypeError: can only concatenate list (not "int") to list

In [19]:
li2 = [1,2,3]

In [20]:
li1 + li2 # this will concatenate the two lists, not perform element-wise addition

[4, 5, 6, 1, 2, 3]

In [21]:
for i in range(len(li1)):
    print(li1[i] + li2[i], end= ' ') # this will perform element-wise addition of the two lists

5 7 9 